"""Add orders table

Revision ID: 37260e893559
Revises: 398e34d3de08
Create Date: 2025-09-07 18:43:50.932095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37260e893559'
down_revision: Union[str, None] = '398e34d3de08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paypal_order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payer_id', sa.String(), nullable=True),
    sa.Column('payer_email', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('return_url', sa.String(), nullable=True),
    sa.Column('cancel_url', sa.String(), nullable=True),
    sa.Column('paypal_response', sa.JSON(), nullable=True),
    sa.Column('approval_url', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['paypal.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='paypal'
    )
    op.create_index(op.f('ix_paypal_orders_paypal_order_id'), 'orders', ['paypal_order_id'], unique=True, schema='paypal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paypal_orders_paypal_order_id'), table_name='orders', schema='paypal')
    op.drop_table('orders', schema='paypal')
    # ### end Alembic commands ###
