"""update orders

Revision ID: a2856750f867
Revises: 37260e893559
Create Date: 2025-09-07 21:14:46.497951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2856750f867'
down_revision: Union[str, None] = '37260e893559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('vault_payment_method_id', sa.Integer(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('payer_name_given', sa.String(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('payer_name_surname', sa.String(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('payer_address_country', sa.String(length=2), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('capture_id', sa.String(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('capture_status', sa.String(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('final_capture', sa.Boolean(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('capture_time', sa.DateTime(timezone=True), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('paypal_fee', sa.Numeric(precision=10, scale=2), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('payment_source', sa.JSON(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('captures', sa.JSON(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('seller_protection', sa.JSON(), nullable=True), schema='paypal')
    op.add_column('orders', sa.Column('paypal_links', sa.JSON(), nullable=True), schema='paypal')
    op.create_index(op.f('ix_paypal_orders_capture_id'), 'orders', ['capture_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_customer_id'), 'orders', ['customer_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_payer_email'), 'orders', ['payer_email'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_payer_id'), 'orders', ['payer_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_reference_id'), 'orders', ['reference_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_status'), 'orders', ['status'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_orders_vault_payment_method_id'), 'orders', ['vault_payment_method_id'], unique=False, schema='paypal')
    op.create_foreign_key(None, 'orders', 'vault_payment_methods', ['vault_payment_method_id'], ['id'], source_schema='paypal', referent_schema='paypal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='paypal', type_='foreignkey')
    op.drop_index(op.f('ix_paypal_orders_vault_payment_method_id'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_status'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_reference_id'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_payer_id'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_payer_email'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_customer_id'), table_name='orders', schema='paypal')
    op.drop_index(op.f('ix_paypal_orders_capture_id'), table_name='orders', schema='paypal')
    op.drop_column('orders', 'paypal_links', schema='paypal')
    op.drop_column('orders', 'seller_protection', schema='paypal')
    op.drop_column('orders', 'captures', schema='paypal')
    op.drop_column('orders', 'payment_source', schema='paypal')
    op.drop_column('orders', 'net_amount', schema='paypal')
    op.drop_column('orders', 'paypal_fee', schema='paypal')
    op.drop_column('orders', 'gross_amount', schema='paypal')
    op.drop_column('orders', 'capture_time', schema='paypal')
    op.drop_column('orders', 'final_capture', schema='paypal')
    op.drop_column('orders', 'capture_status', schema='paypal')
    op.drop_column('orders', 'capture_id', schema='paypal')
    op.drop_column('orders', 'payer_address_country', schema='paypal')
    op.drop_column('orders', 'payer_name_surname', schema='paypal')
    op.drop_column('orders', 'payer_name_given', schema='paypal')
    op.drop_column('orders', 'vault_payment_method_id', schema='paypal')
    # ### end Alembic commands ###
