"""upd payment method

Revision ID: c3c3d373ec37
Revises: a2856750f867
Create Date: 2025-09-08 12:32:08.911026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c3d373ec37'
down_revision: Union[str, None] = 'a2856750f867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_payment_methods', sa.Column('is_active', sa.Boolean(), nullable=True), schema='paypal')
    op.drop_index('ix_paypal_vault_payment_methods_status', table_name='vault_payment_methods', schema='paypal')
    op.drop_column('vault_payment_methods', 'status', schema='paypal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_payment_methods', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True), schema='paypal')
    op.create_index('ix_paypal_vault_payment_methods_status', 'vault_payment_methods', ['status'], unique=False, schema='paypal')
    op.drop_column('vault_payment_methods', 'is_active', schema='paypal')
    # ### end Alembic commands ###
