"""initial migration

Revision ID: d8a6be117466
Revises: 
Create Date: 2025-09-07 16:56:15.118737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a6be117466'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paypal_customer_id', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('default_shipping_address', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='paypal'
    )
    op.create_index(op.f('ix_paypal_customers_email_address'), 'customers', ['email_address'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_customers_paypal_customer_id'), 'customers', ['paypal_customer_id'], unique=True, schema='paypal')
    op.create_table('vault_payment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('paypal_payment_token_id', sa.String(), nullable=False),
    sa.Column('payment_source_type', sa.String(), nullable=False),
    sa.Column('usage_type', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('payer_id', sa.String(), nullable=True),
    sa.Column('permit_multiple_tokens', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paypal_status', sa.String(), nullable=True),
    sa.Column('paypal_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['paypal.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='paypal'
    )
    op.create_index(op.f('ix_paypal_vault_payment_methods_customer_id'), 'vault_payment_methods', ['customer_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_vault_payment_methods_payer_id'), 'vault_payment_methods', ['payer_id'], unique=False, schema='paypal')
    op.create_index(op.f('ix_paypal_vault_payment_methods_paypal_payment_token_id'), 'vault_payment_methods', ['paypal_payment_token_id'], unique=True, schema='paypal')
    op.create_index(op.f('ix_paypal_vault_payment_methods_status'), 'vault_payment_methods', ['status'], unique=False, schema='paypal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paypal_vault_payment_methods_status'), table_name='vault_payment_methods', schema='paypal')
    op.drop_index(op.f('ix_paypal_vault_payment_methods_paypal_payment_token_id'), table_name='vault_payment_methods', schema='paypal')
    op.drop_index(op.f('ix_paypal_vault_payment_methods_payer_id'), table_name='vault_payment_methods', schema='paypal')
    op.drop_index(op.f('ix_paypal_vault_payment_methods_customer_id'), table_name='vault_payment_methods', schema='paypal')
    op.drop_table('vault_payment_methods', schema='paypal')
    op.drop_index(op.f('ix_paypal_customers_paypal_customer_id'), table_name='customers', schema='paypal')
    op.drop_index(op.f('ix_paypal_customers_email_address'), table_name='customers', schema='paypal')
    op.drop_table('customers', schema='paypal')
    # ### end Alembic commands ###
